### ISSUE TITLE
Ground to Image GXP Convergence

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/usgscsm#163]
Add debugging into the exceptions so that we can better understand what is going on with GXP.

**Comment by thareUSGS** [comment]
Still states ground2image not converging but I do have errors. Again I am using 

file: j03_045994_1986_xn_18n282w.cub  (I can attach the JSON ISD again - I think it is on another ticket).
`2019/02/15 14:22:57 File SenSocCsm30SensorModel.cpp 	Line 449 : ERROR : ERROR: UsgsAstroLsSensorModel::groundToImage - Did not converge. Ground point: (219221, -20123.6, -37587.3) Computed image point: (12333.5, 2525) Computed ground point: (219236, -20021.7, -37550.8)`

file (LS): testCTX_16x16.cub (I don't think Tiff files are allowing the JSON to get picked up - this might be a BAE issue - I will write it up). But I need to check the ISD since the camera model didn't even start. This might be the error.
`Line 646 : DEBUG : createSensorModel( ... ) - Unable to create CSM or CSM30 Sensor Model`

File (Framer): EN0221843562M.cub
Looks like ISD is not get the camera model to start-up either (need to review the ISD again.
`2019/02/15 14:52:50 File SenFSensorModelFactory.cpp 	Line 646 : DEBUG : createSensorModel( ... ) - Unable to create CSM or CSM30 Sensor Model`

**Comment by jessemapel** [comment]
I think we should just remove that error check. It's a weird redundant check that requires precision to be <=100m. If it's still over the desired precision, then there really is a problem.

**Comment by jlaura** [comment]
I'll take the framer and have a look. Is the CSM getImageIdentifier error gone?  That would indicate that we are instantiating correctly.

**Comment by thareUSGS** [comment]
Do those numbers look correct?  `(219236, -20021.7, -37550.8)` Are they ECEF? If not, they might be a problem.

**Comment by jlaura** [comment]
What sensor and body? Is that CTX?

**Comment by thareUSGS** [comment]
Yes CTX, here is a subset around those pixel coordinates from a slightly modified "dijittered" ISD for the same file. A run down the center and left are available from this temp. download (150M). ftp://ftpext.usgs.gov/pub/wr/az/flagstaff/thare/GXP_CSM3.3_samples/CTX_CSM_forTEST.zip

`+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|ssSupName|imgRegion|ssImgCentLine_I2G|ssImgCentSamp_I2G|ssDMSLatOG|ssDMSLon180|ssLatOG    |ssLon180   |ssElev|ssImgCentLine_G2I|ssImgCentSamp_G2I|ssSensorDeltaLine|ssSensorDeltaSamp|ss2isisLine_G2I|ss2isisSamp_G2I|isisLatOC  |isislon360 |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|rectJ03_0|122      |3496             |0                |46:38.5   |23:56.5    |18.77734927|77.39902628|0     |3496.000017      |7.49651E-09      |1.66992E-05      |7.49651E-09      |12201.00002    |2501           |18.77734927|77.39902628|
|rectJ03_0|123      |3596             |0                |47:14.3   |23:51.8    |18.7873157 |77.39771631|0     |3595.999944      |-7.04267E-09     |-5.60306E-05     |-7.04267E-09     |12300.99994    |2501           |18.7873157 |77.39771631|
|rectJ03_0|124      |3696             |0                |47:50.2   |23:47.1    |18.79727869|77.39640965|0     |3696.00003       |2.16914E-09      |3.00395E-05      |2.16914E-09      |12401.00003    |2501           |18.79727869|77.39640965|
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+`
Tip: nice site to reformat CSV: http://convertcsv.com/csv-to-flat-file.htm 

Socet SET reporting CSV field names:

// ssImgCentLine_I2G, ssImgCentSamp_I2G:
// SOCET SET image-centered coordinate input to image2ground
//
// ssLatOG, ssLon180, ssElev:
// Ground coordinate lat/lon/Elev result from image2ground
//
// ssImgCentLine_G2I, ssImgCentSamp_G2I:
// image-centered coordinate result from ground2image
//
// ssSensorDeltaLine, ssSensorDeltaSamp
// in pixels, difference in I2G and G2I round-trip.
//
//  isisLatOC, isislon360  (just reporting what ISIS should be in ocentric (and 360). But lats should be the same since we are using a sphere).
//  output Lat/Lon in ocentric from Image2Ground

**Comment by thareUSGS** [comment]
Okay those don't appear to be ECEF coords... 

```
import pyproj
import gdal
lon, lat, alt = 77.398,18.787,0
ecef = pyproj.Proj(proj='geocent', a=3396190, b=3396190)
ecef = pyproj.Proj(proj='geocent', a=3396190, b=3396190)
lla = pyproj.Proj(proj='longlat', a=3396190, b=3396190)
X, Y, Z = pyproj.transform(lla, ecef, lon,lat,alt)
print (X,Y,Z)
```
`701494.3680025652 3137790.904704506 1093746.0427879777`

**Comment by jlaura** [comment]
Are you using the ISD that we provided or another ISD for testing this? If another ISD, what are the results with the ISD that we are providing.

**Comment by thareUSGS** [comment]
Yes the last ISD you created fro pfeffer.
[J03_045994_1986_XN_18N282W.json.txt](https://github.com/USGS-Astrogeology/usgscsm/files/2873174/J03_045994_1986_XN_18N282W.json.txt)

**Comment by jlaura** [comment]
:+1:

**Comment by jessemapel** [comment]
Looking at the camera model, it looks like a units issue with the radii. The software assumes it is in meters at the moment. Maybe changing that will fix it?

**Comment by jlaura** [comment]
Shouldn't the code be doing the conversion? I thought that that was added (I didn't look.)

**Comment by jessemapel** [comment]
It's in the framer but not the line scanner

**Comment by jlaura** [comment]
:+1: ugh...need to get those two standardized.

**Comment by jessemapel** [comment]
I think a lot of that code can be shared between the two of them.

**Comment by jlaura** [comment]
@thareUSGS Here is an ISD to try with the MDIS image

```{"center_ephemeris_time": 366628163.75502384, "detector_center": {"line": 512.5, "sample": 512.5}, "detector_line_summing": 1.0, "detector_sample_summing": 1.0, "focal2pixel_lines": [0.0, 0.0, 71.42857143], "focal2pixel_samples": [0.0, 71.42857143, 0.0], "focal_length_model": {"focal_epsilon": 0.5, "focal_length": 549.2399911991896}, "image_lines": 512.0, "image_samples": 512.0, "interpolation_method": "lagrange", "name_model": "USGS_ASTRO_FRAME_SENSOR_MODEL", "name_platform": "MESSENGER", "name_sensor": "MSGR_MDIS_NAC", "optical_distortion": {"transverse": {"x": [0.0, 1.001854269623802, 0.0, 0.0, -0.0005094440474941111, 0.0, 1.004010471468856e-05, 0.0, 1.004010471468856e-05, 0.0], "y": [0.0, 0.0, 1.0, 0.0009060010594996751, 0.0, 0.0003574842626620758, 0.0, 1.004010471468856e-05, 0.0, 1.004010471468856e-05]}}, "radii": {"semimajor": 2439.4, "semiminor": 2439.4, "unit": "km"}, "reference_height": {"maxheight": 100.0, "minheight": 0.0, "unit": "m"}, "sensor_orientation": {"quaternions": [[0.19960883702545376, -0.9381129907373619, 0.1819043816163698, 0.21682048966809936]]}, "sensor_position": {"positions": [[690620.3467395303, 1089961.1824779825, 2468000.3417484527]], "unit": "m", "velocities": [[937.761107429154, 3195.637015582093, -1598.1044656620395]]}, "starting_detector_line": 1.0, "starting_detector_sample": 9.0, "starting_ephemeris_time": 366628161.7070238, "sun_position": {"positions": [[54692703.73540254, 29522489.74005486, -35107.725797157735]], "unit": "m", "velocities": [[8.332626861192878, -33.4784154473128, 0.012701738712896926]]}}```

**Comment by jessemapel** [comment]
@thareUSGS If you run into the same did not converge error, then merge #180 and re-test with that build artifact.

I'm off to lunch but will be back shortly.

**Comment by jlaura** [comment]
I just ran the following on the framer with the newest build and the ISD above (the one @thareUSGS is using)

```python
for i in range(512):
    for j in range(512):
        ic = csmapi.ImageCoord(i,j)
        gnd = model.imageToGround(ic, 0)
        ic2 = model.groundToImage(gnd)
        assert abs(ic.line - ic2.line) < 1e-10
        assert abs(ic.samp - ic2.samp) < 1e-10
```

No errors thrown.

**Comment by thareUSGS** [comment]
CTX - success -- need to test stereo now. Taco Tuesday!!!!

MDIS still issues with instantiation.
```
2019/02/19 16:20:41 File SenFSensorModelFactory.cpp 	Line 1538 : DEBUG : createCsm30SensorModel( ... ) - createSensorModel( ... ) - Unable to create CSM30 Sensor Model
2019/02/19 16:20:41 File SenFSensorModelFactory.cpp 	Line 146 : ERROR : createSensorModel( ... ) - error initializing sensor. 
2019/02/19 16:20:41 File SenFSensorModelFactory.cpp 	Line 646 : DEBUG : createSensorModel( ... ) - Unable to create CSM or CSM30 Sensor Model
```

**Comment by jessemapel** [comment]
I'm going to close this issue and then make a new issue for the framer not instantiating on GXP.
