### ISSUE TITLE
More robust approximation in LS model

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/usgscsm#360]
Currently ground to image in the LS model uses a linear approximation to get a starting point. We should instead use something like a RPC to generate the initial image point. This will cost a little bit at start up but potentially shave an iteration or two in the search for the correct line.

**Comment by jessemapel** [comment]
I think going with a multi-dimensional spline could also get us a better initial approximation. If it's already available in our version of Eigen, then I think we are good to go ahead with it.

**Comment by oleg-alexandrov** [comment]
I've spent quite a bit of time testing things to figure out if it is worth proceeding with this issue (I think trying to avoid work is a very worthy quality of a programmer.) 

It is true that the current initial approximation can be off by up to 100 pixels (see https://github.com/USGS-Astrogeology/usgscsm/pull/383). I tested it with two LRO NAC testcases and one CTX testcase.

Yet, the secant method starting with this converges universally to within 2 or 3 iterations. Every iteration improves the error by 2 or 3 orders of magnitude.

To beat that, so to go from 3 iterations to only 2, which is a very modest improvement, will require the accuracy of the initial approximation to go down from 10-100 pixels to 0.1 - 1 pixel, which is a very tall order, either with RPC or with splines. 

There is also the thing that the current initial approximation is linear and very predictable. A nonlinear approximation would not be, either with splines or with RPC, unless its domain of validity is clearly defined, which would be some kind of polyhedron in 3D.

This is not an academic point. Any time one uses the ground-to-image logic for mapprojection or bundle adjustment one has to be ready for highly unreasonable ground points, and I've seen very strange things happen if one is not careful (think of a map-projected image with a concentric set of ghost halos around it having twisted chunks of the original image). 

My suggestion is to keep in mind that the linescan model could be made a little faster, but as long as it performs reliably and with just very few iterations to leave things as they are. 

And just for the record, I realized that to compute the RPC approximation of any degree there is no need for a nonlinear solver. In fact, the current logic in setLinearApproximation() would very easy to extend to support that. Given two polynomials with unknown coeffecients P(X) and Q(X) (with X in n dimensions), to find the best fit of P(X_i)/Q(X_i) = Y_i, with i = 1, 2, ..., m, one moves the denominator to the right, getting P(X_i) = Q(X_i) * Y_i, and this becomes a linear regression in the coefficients. (The problem can be made unique by assuming Q(0) = 1.) The Eigen package already can solve such overdetermined systems of equations. 

In particular, the current linear approximation can be extended with little work to a projective one (ratio of 1 degree polynomials), which is more natural, because, as we know, to go from a ground pixel to a image pixel in a pinhole camera one divides by z, which amounts to a projective transform.
