### ISSUE TITLE
Find LRO WAC test data set

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/usgscsm#365]
We need an example/testing dataset for LRO WAC. Preferably, this would be a stereo pair so we can test for consistency with ISIS and that it works with stereo correctly in ASP and Socet GXP.

**Comment by oleg-alexandrov** [comment]
This is hairy business.

First step are easy enough. Visit  https://ode.rsl.wustl.edu/moon/indexproductsearch.aspx, choose Experiment Data Record Wide Angle Camera - Mono, get the IMG. Then, run lrowac2isis. 

This however produces "even" and "odd" cub files, with some lines being in the even cubes and some lines in the odd. Next one calibrates them with ``lrowaccal``. Next is photometric correction, with ``photomet``. I could not find a good pvl file having the right model for WAC, the one mentioned here https://www.lpi.usra.edu/lunar/tools/dems/Ohman_mono-WAC_ISIS_procedure_v1-1.pdf is missing. I cooked up one myself, using the plain Lambertian model and no normalization, which does not work too well, but we have bigger problem somewhere else as can be seen below.

With or without photometric correction, one needs to combine the even and odd cub files, using the ``noseam`` tool. I could only make it work after cam2map. Without cam2map, I do:

noseam fromlist = M119923055ME_nomap.txt to = M119923055ME_nomap.cub  SAMPLES=73 LINES=73

and get: **ERROR** PVL Keyword [Class] does not exist in [Group = Error].

Which is a bummer, as for the CSM model we need raw cub files, not ones after cam2map. 

Then, I ran into the issue that ASP can't at this stage process WAC data, with or without cam2map, which I will need to look into, but that's a little beside the point, since I don't know to remove those junky seams in the raw (unprojected) cub files.

In principle, it should be easy to write a tool to take as input the even and odd cubes, combine their image parts, do a little image processing, if needed, and write them back together with the metadata, unless somebody has better ideas.

Anyhow, here's the state of things were I am for now. Good datasets are:

http://pds.lroc.asu.edu/data/LRO-L-LROC-2-EDR-V1.0/LROLRC_0002/DATA/MAP/2010035/WAC/M119923055ME.IMG
http://pds.lroc.asu.edu/data/LRO-L-LROC-2-EDR-V1.0/LROLRC_0002/DATA/MAP/2010035/WAC/M119929852ME.IMG
http://pds.lroc.asu.edu/data/LRO-L-LROC-2-EDR-V1.0/LROLRC_0002/DATA/MAP/2010035/WAC/M119936622ME.IMG
http://pds.lroc.asu.edu/data/LRO-L-LROC-2-EDR-V1.0/LROLRC_0002/DATA/MAP/2010035/WAC/M119950214ME.IMG

These have the Tycho crater. 

Next steps are, as above, going from img to cub, spiceinit, and lrowaccal. 

This will give a raw cub that could be usable with writing code for CSM, as all the metadata is present, even if the even and odd components are not combined yet. 

I will try to figure out what to do next.

**Comment by oleg-alexandrov** [comment]
Another update. The way pixels are stored in the WAC even and odd images is unusual (it is both odd and very uneven :) Here's a clip of an even image (after calibration but without photometry correction):

![image](https://user-images.githubusercontent.com/1325676/163900864-22309dc8-7f94-4fa7-b51d-0210975e9bb7.png)

The bright thing on the diagonal, from left to right, is meant to be a crater rim. When one zooms out, that becomes more clear:

![image](https://user-images.githubusercontent.com/1325676/163900964-88585569-704a-49c7-ad96-f658d915f0f1.png)

I guess each band needs to be transformed, with earliest rows in a band becoming the latest, and vice versa, before even and odd images are combined (and hoping there's no more to it).

The cam2map ISIS tool can project this correctly, however.

We need a merge tool, and the future CSM model should be aware of what operations this tool will do.

Then one has to verify if among the four images above there is a pair with a good stereo convergence angle. I chose them to be within a couple of hours of each other, so at least the illumination is good.

**Comment by jessemapel** [comment]
Just writing down some stuff I said during stand-up.

The strange crater rim is caused by the increasing line direction being opposite the flight direction. So, on the ground the top line of a framelet is adjacent to the borrom line of the next framelet. In other push frame sensors, like MRO MARCI, we've added the option to flip the framelets on ingest. It results in adjacent lines on the ground being adjacent in the image, but it also adds another thing that has to be properly accounted for in downstream processing.

**Comment by scsides** [comment]
For reference, the option for flipping MARCI framelets has a proposal to remove it,

**Comment by jessemapel** [comment]
We now have functionality where we need it across the different repos so here's a tentative workflow to get an image ready for processing:

1. setup development builds of ALE, USGSCSM, and ISIS
2. Use ISIS to ingest, calibrate, and spiceinit your cubes
3. Optionally photometrically correct the images, I don't know if we have good parameters for this yet. I can reach out to Laz about this if needed.
4. Use framestitch to re-combine your even and odd frames, optionally flip them if it's an ascending orbit like in the example above.
5. Use ale to generate ISDs for your images, the framestitch application will strip the ISIS camera model info off the cubes, so you'll need to pass ALE your un-stitched images. It doesn't matter if you use even or odd.
6. Load your generated ISDs and stitched cubes into your CSM SET

I'm going through this process myself and testing out using metakernels vs using cube tables vs using kernels from spiceinit and will update later.

**Comment by oleg-alexandrov** [comment]
The images and cameras produced by Jesse using the new stitching tool look good. I ran stereo and get plausible results. Documentation and an illustration is here. https://stereopipeline.readthedocs.io/en/latest/examples.html#lunar-reconnaissance-orbiter-lro-wac

There are some artifacts due stitching, which I will study in more detail and open another issue about. More documentation is needed too.  but the task of finding an adequate stereo pair and ensure that CSM and ASP work with it is, I think, done. This could be closed.
